from app.services.agent_1_selector import verify_comparison_viability, classify_part_commodity, auto_select_golden_reference
from app.services.agent_2_triage import process_and_validate
from app.services.agent_3_detector import run_anomaly_ensemble, compute_ssim_diff
from app.services.agent_4_decision import make_decision, fuse_multi_angle_decisions
from app.services.agent_5_explainer import generate_explanation
from app.services.reporting import generate_pdf_report, generate_csv_export
from app.services.embedding_service import extract_image_embedding, cosine_similarity, search_reference_library



